[platformio]
src_dir = devices

; shared env config
[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson @ ^7.0.0
extra_scripts =
    pre:scripts/get_env.py
    

[env:test_sensors]
board = nodemcuv2
src_filter = +<test_sensors/>

