[platformio]
src_dir = devices

; shared env config
[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8

[env:test_sensors]
board = nodemcuv2
src_filter = +<test_sensors/>